services:
  backend:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    working_dir: /app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
