services:
  backend:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    working_dir: /app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    working_dir: /app
    depends_on:
      - backend
